### ISSUE TITLE
Trying to install qrcode-scan

### ISSUE THREAD

**Issue by UrbanFirstNation** [saadel/qrcode-scan#2]
any installation instructions 

default username password ?

any information will be appreciated

**Comment by saadel** [comment]
yeah, just import the sql file: qrcode-scan/mysql/bscan_2014-11-19.sql
and you can login with:  test / 000000

**Comment by UrbanFirstNation** [comment]
Thanks , I already had the file, I had it on the main folder, also on the mysql folder
 but no luck

here is the link http://qrcode.urbanfirstnations.ca/q/

**Comment by saadel** [comment]
no, I mean you need to import it into your database,
create a `bscan` database and then import that file to create the tables and the default user.

**Comment by UrbanFirstNation** [comment]
I was able to import the database, I can see the user test and the hash when I look directly into the database, but when I try to log in and enter the password it does not recognize it.

**Comment by saadel** [comment]
maybe you're using an older version of the project,
even signing up is not working: http://qrcode.urbanfirstnations.ca/q/signup.php
try using the latest version
