### ISSUE TITLE
mysql import error

### ISSUE THREAD

**Issue by eriol61309146** [saadel/qrcode-scan#3]
Hello, I was trying to install the application when I import the sql file it shows the error message:
Error
SQL query:

CREATE TABLE `Infos` (
  `i_id` int(11) NOT NULL AUTO_INCREMENT,
  `i_jour` date DEFAULT NULL,
  `heure_debut` datetime DEFAULT NULL,
  `heure_fin` datetime DEFAULT NULL,
  `u_id` int(4) DEFAULT NULL,
  `ouvrier_o_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`i_id`),
  KEY `FK_Infos_u_id` (`u_id`),
  KEY `FK_Infos_ouvrier_o_id` (`ouvrier_o_id`),
  CONSTRAINT `FK_Infos_ouvrier_o_id` FOREIGN KEY (`ouvrier_o_id`) REFERENCES `ouvrier` (`o_id`),
  CONSTRAINT `FK_Infos_u_id` FOREIGN KEY (`u_id`) REFERENCES `utilisateur` (`u_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
MySQL said: Documentation

#1215 - Cannot add foreign key constraint

If I choose not to Enable foreign key checks, I can import the file however the system will not work.

actually I got the same problem with the previous reported issue, the registration also doesn't work. 
I am pretty sure I downloaded the latest version.
Any ideas?

**Comment by eriol61309146** [comment]
By the way, is there any way that I can create a admin account or do you have a default admin account?

**Comment by eriol61309146** [comment]
FYI: http://qrcode.urbanfirstnations.ca/signup.php
same issue

**Comment by prinsapps** [comment]
same issue error on MySQL import

**Comment by Habib2605** [comment]
c'est la base de données bsan qui a des problemes au niveau des contratintes dans la table infos et la table ouvrier . Essayé avec ce script sql :
-- phpMyAdmin SQL Dump
-- version 4.9.1
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost
-- Généré le :  lun. 02 déc. 2019 à 10:45
-- Version du serveur :  10.4.8-MariaDB
-- Version de PHP :  7.3.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `bscan`
--

-- --------------------------------------------------------

--
-- Structure de la table `chef`
--

CREATE TABLE `chef` (
  `c_id` int(11) NOT NULL,
  `c_nom` varchar(45) DEFAULT NULL,
  `c_prenom` varchar(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `infos` (
  `i_id` int(11) NOT NULL,
  `i_jour` date DEFAULT NULL,
  `heure_debut` datetime DEFAULT NULL,
  `heure_fin` datetime DEFAULT NULL,
  `u_id` int(4) NOT NULL,
  `o_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `ouvrier` (
  `o_id` int(11) NOT NULL,
  `o_nom` varchar(45) DEFAULT NULL,
  `o_prenom` varchar(45) DEFAULT NULL,
  `qrcode` varchar(255) DEFAULT NULL,
  `c_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `utilisateur` (
  `u_id` int(4) NOT NULL,
  `u_nom` varchar(45) DEFAULT NULL,
  `u_prenom` varchar(45) DEFAULT NULL,
  `username` varchar(45) DEFAULT NULL,
  `u_password` varchar(60) DEFAULT NULL,
  `u_validation` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- Index pour la table `chef`
--
ALTER TABLE `chef`
  ADD PRIMARY KEY (`c_id`);

--
-- Index pour la table `infos`
--
ALTER TABLE `infos`
  ADD PRIMARY KEY (`i_id`) USING BTREE,
  ADD KEY `Index FK_infos_ouvrier_o_id_idx` (`o_id`),
  ADD KEY `Index FK_infos_u_id_idx` (`u_id`) USING BTREE;

--
-- Index pour la table `ouvrier`
--
ALTER TABLE `ouvrier`
  ADD PRIMARY KEY (`o_id`,`c_id`),
  ADD KEY `Index FK_ouvrier_c_id_idx` (`c_id`) USING BTREE;

--
-- Index pour la table `utilisateur`
--
ALTER TABLE `utilisateur`
  ADD PRIMARY KEY (`u_id`) USING BTREE;

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `chef`
--
ALTER TABLE `chef`
  MODIFY `c_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT pour la table `infos`
--
ALTER TABLE `infos`
  MODIFY `i_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table `ouvrier`
--
ALTER TABLE `ouvrier`
  MODIFY `o_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- AUTO_INCREMENT pour la table `utilisateur`
--
ALTER TABLE `utilisateur`
  MODIFY `u_id` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `infos`
--
ALTER TABLE `infos`
  ADD CONSTRAINT `Index FK_infos_ouvrier_o_id` FOREIGN KEY (`o_id`) REFERENCES `ouvrier` (`o_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `Index FK_infos_u_id` FOREIGN KEY (`u_id`) REFERENCES `utilisateur` (`u_id`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Contraintes pour la table `ouvrier`
--
ALTER TABLE `ouvrier`
  ADD CONSTRAINT `Index FK_ouvrier_c_id` FOREIGN KEY (`c_id`) REFERENCES `chef` (`c_id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

**Comment by r00tk1ll** [comment]
Try this:

`SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE chef (
c_id int(11) NOT NULL,
c_nom varchar(45) DEFAULT NULL,
c_prenom varchar(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE infos (
i_id int(11) NOT NULL,
i_jour date DEFAULT NULL,
heure_debut datetime DEFAULT NULL,
heure_fin datetime DEFAULT NULL,
u_id int(4) NOT NULL,
o_id int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ouvrier (
o_id int(11) NOT NULL,
o_nom varchar(45) DEFAULT NULL,
o_prenom varchar(45) DEFAULT NULL,
qrcode varchar(255) DEFAULT NULL,
c_id int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE utilisateur (
u_id int(4) NOT NULL,
u_nom varchar(45) DEFAULT NULL,
u_prenom varchar(45) DEFAULT NULL,
username varchar(45) DEFAULT NULL,
u_password varchar(60) DEFAULT NULL,
u_validation int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE chef
ADD PRIMARY KEY (c_id);


ALTER TABLE infos
ADD PRIMARY KEY (i_id) USING BTREE, ADD KEY FK_infos_ouvrier_o_id_idx (o_id), ADD KEY FK_infos_u_id_idx (u_id) USING BTREE;


ALTER TABLE ouvrier
ADD PRIMARY KEY (o_id,c_id),
ADD KEY FK_ouvrier_c_id_idx (c_id) USING BTREE;

ALTER TABLE utilisateur
ADD PRIMARY KEY (u_id) USING BTREE;


ALTER TABLE chef
MODIFY c_id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;


ALTER TABLE infos
MODIFY i_id int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE ouvrier
MODIFY o_id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;


ALTER TABLE utilisateur
MODIFY u_id int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;


ALTER TABLE infos
ADD CONSTRAINT FK_infos_ouvrier_o_id FOREIGN KEY (o_id) REFERENCES ouvrier (o_id) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FK_infos_u_id FOREIGN KEY (u_id) REFERENCES utilisateur (u_id) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE ouvrier
ADD CONSTRAINT FK_ouvrier_c_id FOREIGN KEY (c_id) REFERENCES chef (c_id) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;`
